Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-11, with the labels that each got.

#255 Mpl refacto
  CONTRIBUTING.md
  README.md
  config.yml
  dev-requirements.txt
  mplc/constants.py
  mplc/contributivity.py
  mplc/datasets/dataset_titanic.py
  mplc/mpl_utils.py
  mplc/multi_partner_learning.py
  mplc/partner.py
  mplc/requirements.txt
  mplc/scenario.py
  notebooks/tutorials/Tutorial-1_Run_your_first_scenario.ipynb
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  notebooks/tutorials/Tutorial-3_Use_homemade_dataset.ipynb
  setup.py
  tests/end_to_end_tests.py
  tests/unit_tests.py
Labels: optimization

#262 Refacto datasets
  .gitignore
  mplc/__init__.py
  mplc/dataset.py
  mplc/datasets/__init__.py
  mplc/datasets/dataset_cifar10.py
  mplc/datasets/dataset_esc50.py
  mplc/datasets/dataset_imdb.py
  mplc/datasets/dataset_mnist.py
  mplc/datasets/dataset_titanic.py
  mplc/scenario.py
  tests/unit_tests.py
Labels: optimization

#266 Update the notebook Tutorial-3 according to PR262
  notebooks/tutorials/Tutorial-1_Run_your_first_scenario.ipynb
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  notebooks/tutorials/Tutorial-3_Use_homemade_dataset.ipynb
Labels: documentation

#274 Add epoch number in logs
  mplc/multi_partner_learning.py
Labels: enhancement

#264 Update the documentation (README, documentation, etc.)
  CONTRIBUTING.md
  README.md
  mplc/doc/documentation.md
  mplc/docs/documentation.md
  mplc/partner.py
  notebooks/old_examples_of_results_analysis/contributivity_method_comparison.ipynb
  notebooks/old_examples_of_results_analysis/mpl.ipynb
  notebooks/old_examples_of_results_analysis/mpl_with_losses.ipynb
  notebooks/old_examples_of_results_analysis/run_experiment_on_google_collab.ipynb
  notebooks/run_experiment_on_google_collab.ipynb
  notebooks/tutorials/Tutorial-1_Run_your_first_scenario.ipynb
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  notebooks/tutorials/Tutorial-3_Use_homemade_dataset.ipynb
Labels: documentation, enhancement

#277 Add random and permuted corruption methods
  mplc/partner.py
  mplc/scenario.py
  tests/unit_tests.py
Labels: enhancement

#279 Fix early stopping
  mplc/multi_partner_learning.py
Labels: bug

#283 Change Cifar10's model optimizer
  mplc/dataset.py
Labels: optimization
