Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-12, with the labels that each got.

#263 [demo] Let's rebase
  README.md
Labels: documentation

#280 refacto of corruption, with 2 new methods
  main.py
  mplc/corruption.py
  mplc/doc/documentation.md
  mplc/partner.py
  mplc/scenario.py
  mplc/utils.py
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  tests/unit_tests.py
Labels: enhancement

#275 Experiment object
  CONTRIBUTING.md
  config.yml
  config_quick_debug.yml
  main.py
  mplc/__init__.py
  mplc/constants.py
  mplc/contributivity.py
  mplc/corruption.py
  mplc/dataset.py
  mplc/doc/documentation.md
  mplc/experiment.py
  mplc/mpl_utils.py
  mplc/multi_partner_learning.py
  mplc/partner.py
  mplc/scenario.py
  mplc/utils.py
  notebooks/old_examples_of_results_analysis/contributivity_method_comparison.ipynb
  notebooks/old_examples_of_results_analysis/mpl.ipynb
  notebooks/tutorials/Tutorial-1_Run_your_first_scenario.ipynb
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  setup.py
  tests/config_end_to_end_test_contrib.yml
  tests/end_to_end_tests.py
  tests/unit_tests.py
Labels: enhancement, help wanted

#268 Coverage
  .coverage
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  mplc/doc/documentation.md
Labels: enhancement

#290 upgrade tf version to 2.4
  dev-requirements.txt
  mplc/corruption.py
  mplc/dataset.py
  mplc/mpl_utils.py
  mplc/multi_partner_learning.py
  mplc/partner.py
  mplc/requirements.txt
  tests/unit_tests.py
Labels: dependencies

#281 LFlip refacto in S-model
  mplc/constants.py
  mplc/contributivity.py
  mplc/dataset.py
  mplc/doc/documentation.md
  mplc/models.py
  mplc/multi_partner_learning.py
  mplc/partner.py
  mplc/scenario.py
Labels: optimization

#269 More end to end test
  .travis.yml
  mplc/constants.py
  mplc/experiment.py
  mplc/models.py
  mplc/scenario.py
  tests/config_end_to_end_test_contrib.yml
  tests/contrib_end_to_end_test.py
  tests/ml_perf_end_to_end_tests.py
  tests/test_utils.py
Labels: enhancement

#288 Switch local or global val/test set
  README.md
  config_quick_debug.yml
  mplc/contributivity.py
  mplc/corruption.py
  mplc/dataset.py
  mplc/doc/documentation.md
  mplc/multi_partner_learning.py
  mplc/partner.py
  mplc/scenario.py
  mplc/splitter.py
  mplc/utils.py
  tests/config_end_to_end_test_contrib.yml
  tests/config_end_to_end_test_mnist.yml
  tests/unit_tests.py
Labels: enhancement, nice_to_have

#301 Update s-model related contributivity
  mplc/contributivity.py
Labels: bug
