Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-06, with the labels that each got.

#141 Refactor multi partner learning
  README.md
  config.yml
  config_quick_debug.yml
  contributivity.py
  fl_training.py
  main.py
  multi_partner_learning.py
  requirements.txt
  scenario.py
  utils.py
Labels: optimization

#151 Add a section on how to interact with this project
  README.md
  img/Substra_Logo couleur_RVB_w150px.png
Labels: documentation

#147 Refactor how to handle the dataset and add support for CIFAR10
  README.md
  config.yml
  config_quick_debug.yml
  constants.py
  contributivity.py
  dataset.py
  datasets/__init__.py
  datasets/dataset_cifar10.py
  datasets/dataset_mnist.py
  main.py
  multi_partner_learning.py
  scenario.py
  utils.py
Labels: enhancement

#170 Housekeeping! (clean samples_split_option, clean local val and test sets, misc. minor improvements)
  README.md
  config.yml
  config_quick_debug.yml
  contributivity.py
  main.py
  multi_partner_learning.py
  scenario.py
  utils.py
Labels: enhancement

#164 Run on google collab
  README.md
  main.py
  run_experiment_on_google_collab.ipynb
Labels: enhancement
