Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-09, with the labels that each got.

#198 Logistic regression support for any approach
  config_quick_debug.yml
  datasets/dataset_titanic.py
  multi_partner_learning.py
Labels: enhancement

#230 Update Travis config
  .travis.yml
  tests/end_to_end_tests.py
Labels: enhancement

#215 Flake it!
  .travis.yml
  contributivity.py
  dataset.py
  datasets/dataset_mnist.py
  datasets/dataset_titanic.py
  main.py
  multi_partner_learning.py
  partner.py
  requirements.txt
  scenario.py
  shapley_value/shapley.py
  tests/end_to_end_tests.py
  tests/unit_tests.py
  utils.py
Labels: enhancement, good first issue, help wanted

#223 Add esc 50 dataset a sound classification example
  .gitignore
  README.md
  config.yml
  constants.py
  datasets/dataset.py
  datasets/dataset_cifar10.py
  datasets/dataset_esc50.py
  datasets/dataset_mnist.py
  datasets/dataset_titanic.py
  requirements.txt
  scenario.py
  tests/unit_tests.py
Labels: enhancement

#233 Refacto to pypi package
  .gitignore
  .travis.yml
  config_quick_debug.yml
  datasets/dataset.py
  dev-requirements.txt
  main.py
  notebooks/contributivity_method_comparison.ipynb
  notebooks/examples/1 _INTRO_MNIST.ipynb
  notebooks/examples/2 _Sentiment140.ipynb
  notebooks/examples/3_Exploring_results.ipynb
  notebooks/examples/4_Exploring_contributivity.ipynb
  notebooks/run_experiment_on_google_collab.ipynb
  setup.py
  subtest/__init__.py
  subtest/constants.py
  subtest/contributivity.py
  subtest/datasets/__init__.py
  subtest/datasets/dataset.py
  subtest/datasets/dataset_cifar10.py
  subtest/datasets/dataset_esc50.py
  subtest/datasets/dataset_mnist.py
  subtest/datasets/dataset_titanic.py
  subtest/docs/documentation.md
  subtest/multi_partner_learning.py
  subtest/partner.py
  subtest/requirements.txt
  subtest/scenario.py
  subtest/utils.py
  tests/end_to_end_tests.py
  tests/unit_tests.py
Labels: enhancement, optimization
