Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-08, with the labels that each got.

#203 README TOC
  README.md
Labels: documentation

#204 Format yml config files
  config.yml
  config_quick_debug.yml
Labels: optimization

#166 Iss144 initialize experiment with an existing model
  README.md
  config.yml
  config_quick_debug.yml
  multi_partner_learning.py
  scenario.py
  tests.py
  utils.py
Labels: enhancement

#219 removed typo from root folder
  notebooks/mpl_with_losses.ipynb
Labels: bug
