Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-10, with the labels that each got.

#249 fix bug when generating local_data folder
  mplc/datasets/dataset_esc50.py
  mplc/datasets/dataset_titanic.py
Labels: bug

#253 fix numpy version
  dev-requirements.txt
  mplc/requirements.txt
Labels: bug

#236 Add contributivity methods end to end test
  tests/config_end_to_end_test_contrib.yml
  tests/config_end_to_end_test_mnist.yml
  tests/end_to_end_tests.py
Labels: enhancement

#247 Add partial corruption
  mplc/partner.py
  mplc/scenario.py
Labels: optimization

#239 Federated step by step contributivity methods
  config_quick_debug.yml
  mplc/constants.py
  mplc/contributivity.py
  mplc/docs/documentation.md
Labels: enhancement

#246 Library related improvement
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  mplc/docs/documentation.md
  mplc/requirements.txt
  notebooks/examples/Tutorial_2_Add_contributivity_measurement.ipynb
  notebooks/tutorials/Tutorial-1_Run_your_first_scenario.ipynb
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  notebooks/tutorials/Tutorial-3_Use_homemade_dataset.ipynb
  setup.py
Labels: optimization

#241 Add the PVRL method (rebased)
  mplc/contributivity.py
  mplc/docs/documentation.md
  mplc/multi_partner_learning.py
Labels: enhancement

#248 Add LFlip method
  README.md
  mplc/constants.py
  mplc/contributivity.py
  mplc/docs/documentation.md
  mplc/multi_partner_learning.py
Labels: enhancement, need test

#260 Fix the shuffling of labels
  mplc/partner.py
Labels: bug
