Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-07, with the labels that each got.

#179 Update readme
  README.md
  img/results_graphs_example.png
Labels: documentation

#176 Switch to tf 2.2
  requirements.txt
Labels: need test

#182 Add output messages with the asserts and tests of the config.yml: unkown parameters
  main.py
  scenario.py
  utils.py
Labels: documentation

#197 Proportion of the dataset
  README.md
  config.yml
  config_quick_debug.yml
  scenario.py
  tests.py
Labels: enhancement

#190 Unit test in partner.py - cifar10
  dataset.py
  datasets/dataset_mnist.py
  partner.py
  scenario.py
  tests.py
Labels: enhancement

#185 Adding Titanic Dataset
  README.md
  config_quick_debug.yml
  constants.py
  datasets/dataset_titanic.py
  multi_partner_learning.py
  scenario.py
Labels: enhancement
