Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2020-04, with the labels that each got.

#81 Update and finetune comments
  README.md
  contributivity_measures.py
  fl_training.py
  results.csv
  scenario.py
  simulation_run.py
Labels: documentation

#89 Iss78 contrib method in config
  config.yml
  config_quick_debug.yml
  contributivity_measures.py
  fl_training.py
  scenario.py
  simulation_run.py
Labels: enhancement

#93 Add option for aggregation weighted per local performance
  config_quick_debug.yml
  fl_training.py
  scenario.py
Labels: enhancement

#62 Add IS and stratified method
  config.yml
  config_quick_debug.yml
  contributivity.py
  contributivity_measures.py
  scenario.py
  simulation_run.py
Labels: enhancement

#112 Document config variables and rename node to partner
  README.md
  analyse_results.ipynb
  config.yml
  config_quick_debug.yml
  contributivity.py
  fl_training.py
  main.py
  mnist_fl_examples/mnist_baseline.py
  mnist_fl_examples/mnist_fl.py
  partner.py
  saved_experiments/simple_16/Random_2_2020-03-17_23h15_f0a2b795e3c74f47a0a73419db2aaf1a/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-17_23h30_8c3f62d1c72d401182fe47fb3755d6a1/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-17_23h44_ff8e8529dffa4bbda30cc96fe83a06c3/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_00h02_e53eebed5dcf4eb2ba99d9695a64983c/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_00h18_3271b104167d4f888b8301a99b4d70bc/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_00h32_e80a8278be584b2faf7decc67afaaefc/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_00h50_7938dbe90ef646b3b25852e13441fdc2/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_01h05_29304adce7fd4a44bd7990c2add23695/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_01h20_44f697dee33f46fc9b964a16c93538ba/results_summary.txt
  saved_experiments/simple_16/Random_2_2020-03-18_01h37_944e20f7a5cb4fcebe9d185f49ec73d8/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h00_a5459a4841de4febaf504f4eeee98ebd/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h07_03767e1a440044c6af7be17e873ff190/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h19_a2e9466290ad4273ab4a6185bb396642/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h23_2a2aa2500ed24d258a1831968b77bef6/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h33_2163b6a949514f489113a081d017d7a2/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h38_5bb4e7f7a14d4771b682213e64481920/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h47_e25ba6932cd24894b20e0428e2242b8b/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-17_23h53_0167465b10154e7b948bc557c4a923cc/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h06_931ce9b74f64478798bbd8faac68b408/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h11_dcff3511fd22421fa5ba3a1e57023cbe/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h22_7f8e5b26fd1447aaaaf53ba43aac574a/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h27_7fd6f21a58b349829db5cb8377ebf870/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h37_d1f8a46213064ffea9e3e0074c461623/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h41_876c19e484bb491fa9cc2e0b5182ed05/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h54_9a40293a83e1450998e1a99a9f45b208/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_00h58_f05b87c82a2142219c0a9b0ae8e62b0b/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_01h09_b678776cb7da4b4481c843001bf71599/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_01h14_873d0fa5964d439b9296ddc12eab8be4/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_01h24_ecdd2854b8734ec190e49fdc1c32d04b/results_summary.txt
  saved_experiments/simple_16/Random_3_2020-03-18_01h29_61f2bf7ac70c4db48907925bf2a5f040/results_summary.txt
  saved_experiments/simple_16/config.yml
  saved_experiments/simple_16/results.csv
  scenario.py
  shapley_value/shapley.py
Labels: documentation, nice_to_have

#113 Advanced split of data samples among partners
  README.md
  config_quick_debug.yml
  fl_training.py
  main.py
  partner.py
  scenario.py
  utils.py
Labels: enhancement
