Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2021-09, with the labels that each got.

#337 Change results saving behaviour with results saved by default
  dev-requirements.txt
  mplc/constants.py
  mplc/experiment.py
  mplc/multi_partner_learning/basic_mpl.py
  mplc/requirements.txt
  mplc/scenario.py
  tests/test_utils.py
Labels: bug, enhancement

#352 Add single partner learning to available methods
  .coverage
  mplc/contributivity.py
  mplc/experiment.py
  mplc/multi_partner_learning/__init__.py
  mplc/multi_partner_learning/basic_mpl.py
  tests/ml_perf_end_to_end_tests.py
Labels: bug

#353 Plot data distribution
  img/train_set_corrupted_ground_truth.png
  img/train_set_ground_truth.png
  mplc/doc/documentation.md
  mplc/experiment.py
  mplc/partner.py
  mplc/scenario.py
  mplc/utils.py
  notebooks/reference_scenarios/benchmarks.ipynb
Labels: enhancement

#345 Federated averaging with local and global optimizations
  mplc/doc/documentation.md
  mplc/multi_partner_learning/__init__.py
  mplc/multi_partner_learning/fast_mpl.py
Labels: experiment, need test, optimization
