Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2021-04, with the labels that each got.

#334 Fix typo in config_quick_debug
  config_quick_debug.yml
Labels: bug

#321 Define reference scenarios and initiate benchmark of our different approaches
  README.md
  img/reference_scenarios.png
Labels: experiment

#335 Clarify doc and example code snippet on running an Experiment
  README.md
  mplc/doc/documentation.md
Labels: bug

#338 Testing nightly builds
  .github/workflows/main_ci.yml
Labels: optimization

#315 Faster versions of FedAvg, FedGrads and Smodel.
  config.yml
  config_quick_debug.yml
  mplc/__init__.py
  mplc/constants.py
  mplc/contributivity.py
  mplc/doc/documentation.md
  mplc/models.py
  mplc/multi_partner_learning/__init__.py
  mplc/multi_partner_learning/basic_mpl.py
  mplc/multi_partner_learning/fast_mpl.py
  mplc/multi_partner_learning/utils.py
  mplc/scenario.py
  mplc/utils.py
  notebooks/tutorials/Tutorial-2_Add_contributivity_measurement.ipynb
  notebooks/tutorials/Tutorial-3_Use_homemade_dataset.ipynb
  tests/config_end_to_end_test_contrib.yml
  tests/config_end_to_end_test_mnist.yml
  tests/contrib_end_to_end_test.py
  tests/ml_perf_end_to_end_tests.py
  tests/unit_tests.py
Labels: enhancement, optimization

#336 Tox integration as test runner
  .github/workflows/main_ci.yml
  CONTRIBUTING.md
  Makefile
  dev-requirements.txt
  setup.py
  tox.ini
Labels: enhancement
