Repository SubstraFoundation/distributed-learning-contributivity, pull requests merged in 2021-01, with the labels that each got.

#299 Add gradient fusion method for multi-partner-learning
  mplc/doc/documentation.md
  mplc/mpl_utils.py
  mplc/multi_partner_learning.py
  mplc/partner.py
Labels: enhancement

#311 Fix smodel
  mplc/multi_partner_learning.py
Labels: bug

#313 [build] Fix twine command
  CONTRIBUTING.md
Labels: documentation

#314 Rollback to Python 3.6 & Add 3.6 to gh actions
  .github/workflows/main_ci.yml
  setup.py
Labels: dependencies

#322 Change log format
  mplc/utils.py
Labels: enhancement

#328 Update to TF v2.4.1
  dev-requirements.txt
  mplc/requirements.txt
Labels: dependencies
